<?php

use yii\db\Migration;

class m200624_051745_core_paylog extends Migration
{
    public function up()
    {
        /* 取消外键约束 */
        $this->execute('SET foreign_key_checks = 0');
        
        /* 创建表 */
        $this->createTable('{{%core_paylog}}', [
            'plid' => "bigint(11) unsigned NOT NULL AUTO_INCREMENT",
            'type' => "varchar(20) NOT NULL COMMENT '支付类型'",
            'openid' => "varchar(40) NOT NULL COMMENT 'openid'",
            'uniontid' => "varchar(64) NULL COMMENT '跨应用标识'",
            'tid' => "varchar(128) NULL",
            'fee' => "decimal(10,2) NOT NULL COMMENT '支付金额'",
            'status' => "tinyint(4) NOT NULL COMMENT '支付状态'",
            'module' => "varchar(50) NOT NULL COMMENT '模块'",
            'tag' => "varchar(2000) NOT NULL",
            'is_usecard' => "tinyint(3) unsigned NULL COMMENT '是否使用会员卡'",
            'card_type' => "tinyint(3) unsigned NULL COMMENT '会员卡类型'",
            'card_id' => "varchar(50) NULL COMMENT '会员卡id'",
            'card_fee' => "decimal(10,2) unsigned NULL COMMENT '会员卡余额'",
            'encrypt_code' => "varchar(100) NULL COMMENT '加密字符串'",
            'is_wish' => "tinyint(1) NULL",
            'PRIMARY KEY (`plid`)'
        ], "ENGINE=InnoDB  DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT");
        
        /* 索引设置 */
        $this->createIndex('idx_openid','{{%core_paylog}}','openid',0);
        $this->createIndex('idx_tid','{{%core_paylog}}','tid',0);
        $this->createIndex('uniontid','{{%core_paylog}}','uniontid',0);
        
        
        /* 表数据 */
        $this->insert('{{%core_paylog}}',['plid'=>'9','type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>NULL,'tid'=>NULL,'fee'=>'40.00','status'=>'1','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'10','type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>NULL,'tid'=>NULL,'fee'=>'40.00','status'=>'1','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'11','type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031449995152','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'12','type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031454975355','tid'=>NULL,'fee'=>'80.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'13','type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031455515510','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'14','type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031451100102','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'15','type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031498485155','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'16','type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031410256571','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'17','type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031455524949','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'18','type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031453981005','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'19','type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031452101971','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'20','type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031448514951','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'21','type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031499521004','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'22','type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031451549754','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'23','type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031499525351','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'24','type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031449531001','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'25','type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031453974950','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'26','type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031454511019','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'27','type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031410010198','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'28','type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031410055494','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'29','type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031455535548','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'30','type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031448515797','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'31','type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031497555655','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'32','type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031454574950','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'33','type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031448529799','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'34','type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031453539910','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'35','type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031455515410','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'36','type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031498501005','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'37','type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031410048541','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'38','type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031456495097','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'39','type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031498551005','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'40','type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031448101571','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'41','type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031450571015','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'42','type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031457975110','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'43','type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031451101100','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'44','type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031448565453','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'45','type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031497545051','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'46','type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031410156531','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'47','type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031498525010','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'48','type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031410151995','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'49','type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031451521005','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'50','type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031453579797','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'51','type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031499565256','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'52','type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031410298985','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'53','type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031455525410','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'54','type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031498495352','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'55','type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031452545797','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'56','type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031454971015','tid'=>NULL,'fee'=>'240.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'57','type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031449531009','tid'=>NULL,'fee'=>'0.10','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'58','type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031599501025','tid'=>NULL,'fee'=>'0.10','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'59','type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031555571021','tid'=>NULL,'fee'=>'0.05','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'60','type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031654535557','tid'=>'','fee'=>'0.10','status'=>'1','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'61','type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020031657981005','tid'=>'','fee'=>'0.15','status'=>'1','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'62','type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020032151975653','tid'=>NULL,'fee'=>'0.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'63','type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020032110197100','tid'=>NULL,'fee'=>'0.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'64','type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020032199995652','tid'=>NULL,'fee'=>'280.20','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'65','type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020032157549749','tid'=>NULL,'fee'=>'280.20','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'66','type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020032110156975','tid'=>NULL,'fee'=>'280.20','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'67','type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020032149524850','tid'=>NULL,'fee'=>'280.20','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'68','type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020032154985397','tid'=>NULL,'fee'=>'280.20','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'69','type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020032156100555','tid'=>'','fee'=>'280.20','status'=>'1','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'70','type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020032553100102','tid'=>NULL,'fee'=>'50.05','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'71','type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020032510053565','tid'=>NULL,'fee'=>'80.10','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'72','type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020032599975597','tid'=>NULL,'fee'=>'80.20','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'73','type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020032598545751','tid'=>NULL,'fee'=>'40.05','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'74','type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020032557974851','tid'=>NULL,'fee'=>'40.05','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'75','type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020032551565198','tid'=>NULL,'fee'=>'40.05','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'76','type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020032549499757','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'77','type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020032749485450','tid'=>NULL,'fee'=>'80.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'78','type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020032753565110','tid'=>NULL,'fee'=>'40.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'79','type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020033010010199','tid'=>NULL,'fee'=>'40.05','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'80','type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020033054544897','tid'=>NULL,'fee'=>'40.15','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'81','type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020040151971015','tid'=>NULL,'fee'=>'130.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'82','type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020041149521001','tid'=>NULL,'fee'=>'18.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'83','type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020041598535649','tid'=>NULL,'fee'=>'3280.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'84','type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020041654481014','tid'=>NULL,'fee'=>'1000.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'85','type'=>'wechat','openid'=>'oE5EC0Uvc4QkT_TgcfhgSfpO4LLQ','uniontid'=>'2020041651579957','tid'=>NULL,'fee'=>'200.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'86','type'=>'wechat','openid'=>'oE5EC0aRDVDME1L39dYWzt9bUGlI','uniontid'=>'2020041650565248','tid'=>NULL,'fee'=>'601.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'87','type'=>'wechat','openid'=>'oE5EC0S5K7EMf1tCf1S3tIBXIbCw','uniontid'=>'2020041697569856','tid'=>NULL,'fee'=>'200.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'88','type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020041753535752','tid'=>NULL,'fee'=>'1697.50','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'89','type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020042948544910','tid'=>NULL,'fee'=>'600.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'90','type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020042955101565','tid'=>NULL,'fee'=>'402.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'91','type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020042997524957','tid'=>NULL,'fee'=>'402.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'92','type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020042910053495','tid'=>NULL,'fee'=>'357.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'93','type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020042952541025','tid'=>NULL,'fee'=>'357.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'94','type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020051152971025','tid'=>NULL,'fee'=>'600.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        $this->insert('{{%core_paylog}}',['plid'=>'95','type'=>'wechat','openid'=>'oE5EC0aqNTAdAXpPfikBpkHiSG1o','uniontid'=>'2020051152559999','tid'=>NULL,'fee'=>'600.00','status'=>'0','module'=>'diandi_shop','tag'=>'小程序下单','is_usecard'=>NULL,'card_type'=>NULL,'card_id'=>NULL,'card_fee'=>NULL,'encrypt_code'=>NULL,'is_wish'=>NULL]);
        
        /* 设置外键约束 */
        $this->execute('SET foreign_key_checks = 1;');
    }

    public function down()
    {
        $this->execute('SET foreign_key_checks = 0');
        /* 删除表 */
        $this->dropTable('{{%core_paylog}}');
        $this->execute('SET foreign_key_checks = 1;');
    }
}

