<?php

use yii\db\Migration;

class m200624_051745_member_account extends Migration
{
    public function up()
    {
        /* 取消外键约束 */
        $this->execute('SET foreign_key_checks = 0');
        
        /* 创建表 */
        $this->createTable('{{%member_account}}', [
            'id' => "int(10) unsigned NOT NULL AUTO_INCREMENT",
            'merchant_id' => "int(10) unsigned NULL DEFAULT '0' COMMENT '商户id'",
            'member_id' => "int(10) unsigned NULL DEFAULT '0' COMMENT '用户id'",
            'level' => "int(11) NULL DEFAULT '-1' COMMENT '会员等级'",
            'user_money' => "decimal(10,2) NULL DEFAULT '0.00' COMMENT '当前余额'",
            'accumulate_money' => "decimal(10,2) NULL DEFAULT '0.00' COMMENT '累计余额'",
            'give_money' => "decimal(10,2) NULL DEFAULT '0.00' COMMENT '累计赠送余额'",
            'consume_money' => "decimal(10,2) NULL DEFAULT '0.00' COMMENT '累计消费金额'",
            'frozen_money' => "decimal(10,2) NULL DEFAULT '0.00' COMMENT '冻结金额'",
            'user_integral' => "int(11) NULL DEFAULT '0' COMMENT '当前积分'",
            'accumulate_integral' => "int(11) NULL DEFAULT '0' COMMENT '累计积分'",
            'give_integral' => "int(11) NULL DEFAULT '0' COMMENT '累计赠送积分'",
            'consume_integral' => "decimal(10,2) NULL DEFAULT '0.00' COMMENT '累计消费积分'",
            'frozen_integral' => "int(11) NULL DEFAULT '0' COMMENT '冻结积分'",
            'status' => "tinyint(4) NULL DEFAULT '1' COMMENT '状态[-1:删除;0:禁用;1启用]'",
            'PRIMARY KEY (`id`)'
        ], "ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 ROW_FORMAT=COMPACT COMMENT='会员_账户统计表'");
        
        /* 索引设置 */
        $this->createIndex('member_id','{{%member_account}}','member_id',0);
        
        
        /* 表数据 */
        $this->insert('{{%member_account}}',['id'=>'16','merchant_id'=>'0','member_id'=>'46','level'=>'1','user_money'=>'0.00','accumulate_money'=>'0.00','give_money'=>'0.00','consume_money'=>'0.00','frozen_money'=>'0.00','user_integral'=>'0','accumulate_integral'=>'0','give_integral'=>'0','consume_integral'=>'0.00','frozen_integral'=>'0','status'=>'1']);
        $this->insert('{{%member_account}}',['id'=>'17','merchant_id'=>'0','member_id'=>'47','level'=>'1','user_money'=>'0.00','accumulate_money'=>'0.00','give_money'=>'0.00','consume_money'=>'0.00','frozen_money'=>'0.00','user_integral'=>'0','accumulate_integral'=>'0','give_integral'=>'0','consume_integral'=>'0.00','frozen_integral'=>'0','status'=>'1']);
        $this->insert('{{%member_account}}',['id'=>'18','merchant_id'=>'0','member_id'=>'48','level'=>'1','user_money'=>'0.00','accumulate_money'=>'0.00','give_money'=>'0.00','consume_money'=>'0.00','frozen_money'=>'0.00','user_integral'=>'0','accumulate_integral'=>'0','give_integral'=>'0','consume_integral'=>'0.00','frozen_integral'=>'0','status'=>'1']);
        $this->insert('{{%member_account}}',['id'=>'19','merchant_id'=>'0','member_id'=>'49','level'=>'1','user_money'=>'0.00','accumulate_money'=>'0.00','give_money'=>'0.00','consume_money'=>'0.00','frozen_money'=>'0.00','user_integral'=>'0','accumulate_integral'=>'0','give_integral'=>'0','consume_integral'=>'0.00','frozen_integral'=>'0','status'=>'1']);
        $this->insert('{{%member_account}}',['id'=>'20','merchant_id'=>'0','member_id'=>'50','level'=>'1','user_money'=>'0.00','accumulate_money'=>'0.00','give_money'=>'0.00','consume_money'=>'0.00','frozen_money'=>'0.00','user_integral'=>'0','accumulate_integral'=>'0','give_integral'=>'0','consume_integral'=>'0.00','frozen_integral'=>'0','status'=>'1']);
        $this->insert('{{%member_account}}',['id'=>'21','merchant_id'=>'0','member_id'=>'51','level'=>'1','user_money'=>'0.00','accumulate_money'=>'0.00','give_money'=>'0.00','consume_money'=>'0.00','frozen_money'=>'0.00','user_integral'=>'0','accumulate_integral'=>'0','give_integral'=>'0','consume_integral'=>'0.00','frozen_integral'=>'0','status'=>'1']);
        $this->insert('{{%member_account}}',['id'=>'22','merchant_id'=>'0','member_id'=>'52','level'=>'1','user_money'=>'0.00','accumulate_money'=>'0.00','give_money'=>'0.00','consume_money'=>'0.00','frozen_money'=>'0.00','user_integral'=>'0','accumulate_integral'=>'0','give_integral'=>'0','consume_integral'=>'0.00','frozen_integral'=>'0','status'=>'1']);
        $this->insert('{{%member_account}}',['id'=>'23','merchant_id'=>'0','member_id'=>'53','level'=>'1','user_money'=>'0.00','accumulate_money'=>'0.00','give_money'=>'0.00','consume_money'=>'0.00','frozen_money'=>'0.00','user_integral'=>'0','accumulate_integral'=>'0','give_integral'=>'0','consume_integral'=>'0.00','frozen_integral'=>'0','status'=>'1']);
        $this->insert('{{%member_account}}',['id'=>'24','merchant_id'=>'0','member_id'=>'54','level'=>'1','user_money'=>'0.00','accumulate_money'=>'0.00','give_money'=>'0.00','consume_money'=>'0.00','frozen_money'=>'0.00','user_integral'=>'0','accumulate_integral'=>'0','give_integral'=>'0','consume_integral'=>'0.00','frozen_integral'=>'0','status'=>'1']);
        $this->insert('{{%member_account}}',['id'=>'25','merchant_id'=>'0','member_id'=>'55','level'=>'1','user_money'=>'0.00','accumulate_money'=>'0.00','give_money'=>'0.00','consume_money'=>'0.00','frozen_money'=>'0.00','user_integral'=>'0','accumulate_integral'=>'0','give_integral'=>'0','consume_integral'=>'0.00','frozen_integral'=>'0','status'=>'1']);
        $this->insert('{{%member_account}}',['id'=>'26','merchant_id'=>'0','member_id'=>'56','level'=>'1','user_money'=>'0.00','accumulate_money'=>'0.00','give_money'=>'0.00','consume_money'=>'0.00','frozen_money'=>'0.00','user_integral'=>'0','accumulate_integral'=>'0','give_integral'=>'0','consume_integral'=>'0.00','frozen_integral'=>'0','status'=>'1']);
        $this->insert('{{%member_account}}',['id'=>'27','merchant_id'=>'0','member_id'=>'58','level'=>'1','user_money'=>'0.00','accumulate_money'=>'0.00','give_money'=>'0.00','consume_money'=>'0.00','frozen_money'=>'0.00','user_integral'=>'0','accumulate_integral'=>'0','give_integral'=>'0','consume_integral'=>'0.00','frozen_integral'=>'0','status'=>'1']);
        $this->insert('{{%member_account}}',['id'=>'29','merchant_id'=>'0','member_id'=>'60','level'=>'1','user_money'=>'0.00','accumulate_money'=>'0.00','give_money'=>'0.00','consume_money'=>'0.00','frozen_money'=>'0.00','user_integral'=>'0','accumulate_integral'=>'0','give_integral'=>'0','consume_integral'=>'0.00','frozen_integral'=>'0','status'=>'1']);
        $this->insert('{{%member_account}}',['id'=>'30','merchant_id'=>'0','member_id'=>'61','level'=>'1','user_money'=>'0.00','accumulate_money'=>'0.00','give_money'=>'0.00','consume_money'=>'0.00','frozen_money'=>'0.00','user_integral'=>'0','accumulate_integral'=>'0','give_integral'=>'0','consume_integral'=>'0.00','frozen_integral'=>'0','status'=>'1']);
        $this->insert('{{%member_account}}',['id'=>'31','merchant_id'=>'0','member_id'=>'62','level'=>'1','user_money'=>'0.00','accumulate_money'=>'0.00','give_money'=>'0.00','consume_money'=>'0.00','frozen_money'=>'0.00','user_integral'=>'0','accumulate_integral'=>'0','give_integral'=>'0','consume_integral'=>'0.00','frozen_integral'=>'0','status'=>'1']);
        $this->insert('{{%member_account}}',['id'=>'32','merchant_id'=>'0','member_id'=>'63','level'=>'1','user_money'=>'0.00','accumulate_money'=>'0.00','give_money'=>'0.00','consume_money'=>'0.00','frozen_money'=>'0.00','user_integral'=>'0','accumulate_integral'=>'0','give_integral'=>'0','consume_integral'=>'0.00','frozen_integral'=>'0','status'=>'1']);
        $this->insert('{{%member_account}}',['id'=>'33','merchant_id'=>'0','member_id'=>'64','level'=>'1','user_money'=>'0.00','accumulate_money'=>'0.00','give_money'=>'0.00','consume_money'=>'0.00','frozen_money'=>'0.00','user_integral'=>'0','accumulate_integral'=>'0','give_integral'=>'0','consume_integral'=>'0.00','frozen_integral'=>'0','status'=>'1']);
        $this->insert('{{%member_account}}',['id'=>'34','merchant_id'=>'0','member_id'=>'65','level'=>'1','user_money'=>'0.00','accumulate_money'=>'0.00','give_money'=>'0.00','consume_money'=>'0.00','frozen_money'=>'0.00','user_integral'=>'0','accumulate_integral'=>'0','give_integral'=>'0','consume_integral'=>'0.00','frozen_integral'=>'0','status'=>'1']);
        $this->insert('{{%member_account}}',['id'=>'35','merchant_id'=>'0','member_id'=>'66','level'=>'1','user_money'=>'0.00','accumulate_money'=>'0.00','give_money'=>'0.00','consume_money'=>'0.00','frozen_money'=>'0.00','user_integral'=>'0','accumulate_integral'=>'0','give_integral'=>'0','consume_integral'=>'0.00','frozen_integral'=>'0','status'=>'1']);
        $this->insert('{{%member_account}}',['id'=>'36','merchant_id'=>'0','member_id'=>'67','level'=>'1','user_money'=>'0.00','accumulate_money'=>'0.00','give_money'=>'0.00','consume_money'=>'0.00','frozen_money'=>'0.00','user_integral'=>'0','accumulate_integral'=>'0','give_integral'=>'0','consume_integral'=>'0.00','frozen_integral'=>'0','status'=>'1']);
        $this->insert('{{%member_account}}',['id'=>'37','merchant_id'=>'0','member_id'=>'68','level'=>'1','user_money'=>'0.00','accumulate_money'=>'0.00','give_money'=>'0.00','consume_money'=>'0.00','frozen_money'=>'0.00','user_integral'=>'0','accumulate_integral'=>'0','give_integral'=>'0','consume_integral'=>'0.00','frozen_integral'=>'0','status'=>'1']);
        $this->insert('{{%member_account}}',['id'=>'38','merchant_id'=>'0','member_id'=>'69','level'=>'1','user_money'=>'0.00','accumulate_money'=>'0.00','give_money'=>'0.00','consume_money'=>'0.00','frozen_money'=>'0.00','user_integral'=>'0','accumulate_integral'=>'0','give_integral'=>'0','consume_integral'=>'0.00','frozen_integral'=>'0','status'=>'1']);
        $this->insert('{{%member_account}}',['id'=>'39','merchant_id'=>'0','member_id'=>'70','level'=>'1','user_money'=>'0.00','accumulate_money'=>'0.00','give_money'=>'0.00','consume_money'=>'0.00','frozen_money'=>'0.00','user_integral'=>'0','accumulate_integral'=>'0','give_integral'=>'0','consume_integral'=>'0.00','frozen_integral'=>'0','status'=>'1']);
        $this->insert('{{%member_account}}',['id'=>'40','merchant_id'=>'0','member_id'=>'71','level'=>'1','user_money'=>'0.00','accumulate_money'=>'0.00','give_money'=>'0.00','consume_money'=>'0.00','frozen_money'=>'0.00','user_integral'=>'0','accumulate_integral'=>'0','give_integral'=>'0','consume_integral'=>'0.00','frozen_integral'=>'0','status'=>'1']);
        $this->insert('{{%member_account}}',['id'=>'41','merchant_id'=>'0','member_id'=>'72','level'=>'1','user_money'=>'0.00','accumulate_money'=>'0.00','give_money'=>'0.00','consume_money'=>'0.00','frozen_money'=>'0.00','user_integral'=>'0','accumulate_integral'=>'0','give_integral'=>'0','consume_integral'=>'0.00','frozen_integral'=>'0','status'=>'1']);
        $this->insert('{{%member_account}}',['id'=>'42','merchant_id'=>'0','member_id'=>'73','level'=>'1','user_money'=>'0.00','accumulate_money'=>'0.00','give_money'=>'0.00','consume_money'=>'0.00','frozen_money'=>'0.00','user_integral'=>'0','accumulate_integral'=>'0','give_integral'=>'0','consume_integral'=>'0.00','frozen_integral'=>'0','status'=>'1']);
        $this->insert('{{%member_account}}',['id'=>'43','merchant_id'=>'0','member_id'=>'74','level'=>'1','user_money'=>'0.00','accumulate_money'=>'0.00','give_money'=>'0.00','consume_money'=>'0.00','frozen_money'=>'0.00','user_integral'=>'0','accumulate_integral'=>'0','give_integral'=>'0','consume_integral'=>'0.00','frozen_integral'=>'0','status'=>'1']);
        $this->insert('{{%member_account}}',['id'=>'44','merchant_id'=>'0','member_id'=>'75','level'=>'1','user_money'=>'0.00','accumulate_money'=>'0.00','give_money'=>'0.00','consume_money'=>'0.00','frozen_money'=>'0.00','user_integral'=>'0','accumulate_integral'=>'0','give_integral'=>'0','consume_integral'=>'0.00','frozen_integral'=>'0','status'=>'1']);
        $this->insert('{{%member_account}}',['id'=>'45','merchant_id'=>'0','member_id'=>'76','level'=>'1','user_money'=>'0.00','accumulate_money'=>'0.00','give_money'=>'0.00','consume_money'=>'0.00','frozen_money'=>'0.00','user_integral'=>'0','accumulate_integral'=>'0','give_integral'=>'0','consume_integral'=>'0.00','frozen_integral'=>'0','status'=>'1']);
        $this->insert('{{%member_account}}',['id'=>'46','merchant_id'=>'0','member_id'=>'77','level'=>'1','user_money'=>'0.00','accumulate_money'=>'0.00','give_money'=>'0.00','consume_money'=>'0.00','frozen_money'=>'0.00','user_integral'=>'0','accumulate_integral'=>'0','give_integral'=>'0','consume_integral'=>'0.00','frozen_integral'=>'0','status'=>'1']);
        $this->insert('{{%member_account}}',['id'=>'47','merchant_id'=>'0','member_id'=>'78','level'=>'1','user_money'=>'0.00','accumulate_money'=>'0.00','give_money'=>'0.00','consume_money'=>'0.00','frozen_money'=>'0.00','user_integral'=>'0','accumulate_integral'=>'0','give_integral'=>'0','consume_integral'=>'0.00','frozen_integral'=>'0','status'=>'1']);
        $this->insert('{{%member_account}}',['id'=>'48','merchant_id'=>'0','member_id'=>'79','level'=>'1','user_money'=>'0.00','accumulate_money'=>'0.00','give_money'=>'0.00','consume_money'=>'0.00','frozen_money'=>'0.00','user_integral'=>'0','accumulate_integral'=>'0','give_integral'=>'0','consume_integral'=>'0.00','frozen_integral'=>'0','status'=>'1']);
        $this->insert('{{%member_account}}',['id'=>'49','merchant_id'=>'0','member_id'=>'80','level'=>'1','user_money'=>'0.00','accumulate_money'=>'0.00','give_money'=>'0.00','consume_money'=>'0.00','frozen_money'=>'0.00','user_integral'=>'0','accumulate_integral'=>'0','give_integral'=>'0','consume_integral'=>'0.00','frozen_integral'=>'0','status'=>'1']);
        $this->insert('{{%member_account}}',['id'=>'50','merchant_id'=>'0','member_id'=>'81','level'=>'1','user_money'=>'0.00','accumulate_money'=>'0.00','give_money'=>'0.00','consume_money'=>'0.00','frozen_money'=>'0.00','user_integral'=>'0','accumulate_integral'=>'0','give_integral'=>'0','consume_integral'=>'0.00','frozen_integral'=>'0','status'=>'1']);
        $this->insert('{{%member_account}}',['id'=>'51','merchant_id'=>'0','member_id'=>'82','level'=>'1','user_money'=>'0.00','accumulate_money'=>'0.00','give_money'=>'0.00','consume_money'=>'0.00','frozen_money'=>'0.00','user_integral'=>'0','accumulate_integral'=>'0','give_integral'=>'0','consume_integral'=>'0.00','frozen_integral'=>'0','status'=>'1']);
        $this->insert('{{%member_account}}',['id'=>'52','merchant_id'=>'0','member_id'=>'83','level'=>'1','user_money'=>'0.00','accumulate_money'=>'0.00','give_money'=>'0.00','consume_money'=>'0.00','frozen_money'=>'0.00','user_integral'=>'0','accumulate_integral'=>'0','give_integral'=>'0','consume_integral'=>'0.00','frozen_integral'=>'0','status'=>'1']);
        $this->insert('{{%member_account}}',['id'=>'53','merchant_id'=>'0','member_id'=>'84','level'=>'1','user_money'=>'0.00','accumulate_money'=>'0.00','give_money'=>'0.00','consume_money'=>'0.00','frozen_money'=>'0.00','user_integral'=>'0','accumulate_integral'=>'0','give_integral'=>'0','consume_integral'=>'0.00','frozen_integral'=>'0','status'=>'1']);
        $this->insert('{{%member_account}}',['id'=>'54','merchant_id'=>'0','member_id'=>'85','level'=>'1','user_money'=>'0.00','accumulate_money'=>'0.00','give_money'=>'0.00','consume_money'=>'0.00','frozen_money'=>'0.00','user_integral'=>'0','accumulate_integral'=>'0','give_integral'=>'0','consume_integral'=>'0.00','frozen_integral'=>'0','status'=>'1']);
        $this->insert('{{%member_account}}',['id'=>'55','merchant_id'=>'0','member_id'=>'86','level'=>'1','user_money'=>'0.00','accumulate_money'=>'0.00','give_money'=>'0.00','consume_money'=>'0.00','frozen_money'=>'0.00','user_integral'=>'0','accumulate_integral'=>'0','give_integral'=>'0','consume_integral'=>'0.00','frozen_integral'=>'0','status'=>'1']);
        $this->insert('{{%member_account}}',['id'=>'56','merchant_id'=>'0','member_id'=>'87','level'=>'1','user_money'=>'0.00','accumulate_money'=>'0.00','give_money'=>'0.00','consume_money'=>'0.00','frozen_money'=>'0.00','user_integral'=>'0','accumulate_integral'=>'0','give_integral'=>'0','consume_integral'=>'0.00','frozen_integral'=>'0','status'=>'1']);
        $this->insert('{{%member_account}}',['id'=>'57','merchant_id'=>'0','member_id'=>'88','level'=>'1','user_money'=>'0.00','accumulate_money'=>'0.00','give_money'=>'0.00','consume_money'=>'0.00','frozen_money'=>'0.00','user_integral'=>'0','accumulate_integral'=>'0','give_integral'=>'0','consume_integral'=>'0.00','frozen_integral'=>'0','status'=>'1']);
        $this->insert('{{%member_account}}',['id'=>'58','merchant_id'=>'0','member_id'=>'89','level'=>'1','user_money'=>'0.00','accumulate_money'=>'0.00','give_money'=>'0.00','consume_money'=>'0.00','frozen_money'=>'0.00','user_integral'=>'0','accumulate_integral'=>'0','give_integral'=>'0','consume_integral'=>'0.00','frozen_integral'=>'0','status'=>'1']);
        $this->insert('{{%member_account}}',['id'=>'59','merchant_id'=>'0','member_id'=>'90','level'=>'1','user_money'=>'0.00','accumulate_money'=>'0.00','give_money'=>'0.00','consume_money'=>'0.00','frozen_money'=>'0.00','user_integral'=>'0','accumulate_integral'=>'0','give_integral'=>'0','consume_integral'=>'0.00','frozen_integral'=>'0','status'=>'1']);
        $this->insert('{{%member_account}}',['id'=>'60','merchant_id'=>'0','member_id'=>'91','level'=>'1','user_money'=>'0.00','accumulate_money'=>'0.00','give_money'=>'0.00','consume_money'=>'0.00','frozen_money'=>'0.00','user_integral'=>'0','accumulate_integral'=>'0','give_integral'=>'0','consume_integral'=>'0.00','frozen_integral'=>'0','status'=>'1']);
        $this->insert('{{%member_account}}',['id'=>'61','merchant_id'=>'0','member_id'=>'92','level'=>'1','user_money'=>'0.00','accumulate_money'=>'0.00','give_money'=>'0.00','consume_money'=>'0.00','frozen_money'=>'0.00','user_integral'=>'0','accumulate_integral'=>'0','give_integral'=>'0','consume_integral'=>'0.00','frozen_integral'=>'0','status'=>'1']);
        $this->insert('{{%member_account}}',['id'=>'62','merchant_id'=>'0','member_id'=>'93','level'=>'1','user_money'=>'0.00','accumulate_money'=>'0.00','give_money'=>'0.00','consume_money'=>'0.00','frozen_money'=>'0.00','user_integral'=>'0','accumulate_integral'=>'0','give_integral'=>'0','consume_integral'=>'0.00','frozen_integral'=>'0','status'=>'1']);
        $this->insert('{{%member_account}}',['id'=>'63','merchant_id'=>'0','member_id'=>'94','level'=>'1','user_money'=>'0.00','accumulate_money'=>'0.00','give_money'=>'0.00','consume_money'=>'0.00','frozen_money'=>'0.00','user_integral'=>'0','accumulate_integral'=>'0','give_integral'=>'0','consume_integral'=>'0.00','frozen_integral'=>'0','status'=>'1']);
        $this->insert('{{%member_account}}',['id'=>'64','merchant_id'=>'0','member_id'=>'95','level'=>'1','user_money'=>'0.00','accumulate_money'=>'0.00','give_money'=>'0.00','consume_money'=>'0.00','frozen_money'=>'0.00','user_integral'=>'0','accumulate_integral'=>'0','give_integral'=>'0','consume_integral'=>'0.00','frozen_integral'=>'0','status'=>'1']);
        $this->insert('{{%member_account}}',['id'=>'65','merchant_id'=>'0','member_id'=>'96','level'=>'1','user_money'=>'0.00','accumulate_money'=>'0.00','give_money'=>'0.00','consume_money'=>'0.00','frozen_money'=>'0.00','user_integral'=>'0','accumulate_integral'=>'0','give_integral'=>'0','consume_integral'=>'0.00','frozen_integral'=>'0','status'=>'1']);
        $this->insert('{{%member_account}}',['id'=>'66','merchant_id'=>'0','member_id'=>'97','level'=>'1','user_money'=>'0.00','accumulate_money'=>'0.00','give_money'=>'0.00','consume_money'=>'0.00','frozen_money'=>'0.00','user_integral'=>'0','accumulate_integral'=>'0','give_integral'=>'0','consume_integral'=>'0.00','frozen_integral'=>'0','status'=>'1']);
        $this->insert('{{%member_account}}',['id'=>'67','merchant_id'=>'0','member_id'=>'98','level'=>'1','user_money'=>'0.00','accumulate_money'=>'0.00','give_money'=>'0.00','consume_money'=>'0.00','frozen_money'=>'0.00','user_integral'=>'0','accumulate_integral'=>'0','give_integral'=>'0','consume_integral'=>'0.00','frozen_integral'=>'0','status'=>'1']);
        $this->insert('{{%member_account}}',['id'=>'68','merchant_id'=>'0','member_id'=>'99','level'=>'1','user_money'=>'0.00','accumulate_money'=>'0.00','give_money'=>'0.00','consume_money'=>'0.00','frozen_money'=>'0.00','user_integral'=>'0','accumulate_integral'=>'0','give_integral'=>'0','consume_integral'=>'0.00','frozen_integral'=>'0','status'=>'1']);
        $this->insert('{{%member_account}}',['id'=>'69','merchant_id'=>'0','member_id'=>'100','level'=>'1','user_money'=>'0.00','accumulate_money'=>'0.00','give_money'=>'0.00','consume_money'=>'0.00','frozen_money'=>'0.00','user_integral'=>'0','accumulate_integral'=>'0','give_integral'=>'0','consume_integral'=>'0.00','frozen_integral'=>'0','status'=>'1']);
        $this->insert('{{%member_account}}',['id'=>'70','merchant_id'=>'0','member_id'=>'101','level'=>'1','user_money'=>'0.00','accumulate_money'=>'0.00','give_money'=>'0.00','consume_money'=>'0.00','frozen_money'=>'0.00','user_integral'=>'0','accumulate_integral'=>'0','give_integral'=>'0','consume_integral'=>'0.00','frozen_integral'=>'0','status'=>'1']);
        
        /* 设置外键约束 */
        $this->execute('SET foreign_key_checks = 1;');
    }

    public function down()
    {
        $this->execute('SET foreign_key_checks = 0');
        /* 删除表 */
        $this->dropTable('{{%member_account}}');
        $this->execute('SET foreign_key_checks = 1;');
    }
}

